version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: china
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/china
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
