"""create characters table

Revision ID: 6491264d7827
Revises: 
Create Date: 2025-05-09 14:41:41.994813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6491264d7827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('jyutping', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('stroke_order', sa.String(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('familiarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_character'), 'characters', ['character'], unique=True)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_character'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
