hsk1_words = [
    {'character': '爱', 'pinyin': 'ài', 'definition': 'love'},
    {'character': '爱好', 'pinyin': 'ài hào', 'definition': 'hobby'},
    {'character': '八', 'pinyin': 'bā', 'definition': 'eight'},
    {'character': '爸爸｜爸', 'pinyin': 'bàba', 'definition': 'bà dad'},
    {'character': '吧', 'pinyin': 'ba', 'definition': '(interjection particle)'},
    {'character': '白（形）', 'pinyin': 'bái', 'definition': 'white'},
    {'character': '白天', 'pinyin': 'bái tiān', 'definition': 'day'},
    {'character': '百', 'pinyin': 'bǎi', 'definition': 'hundred'},
    {'character': '班', 'pinyin': 'bān', 'definition': 'class'},
    {'character': '半', 'pinyin': 'bàn', 'definition': 'half'},
    {'character': '半年', 'pinyin': 'bàn nián  half a', 'definition': 'year'},
    {'character': '半天', 'pinyin': 'bàn tiān  half', 'definition': 'day'},
    {'character': '帮', 'pinyin': 'bāng', 'definition': 'help'},
    {'character': '帮忙', 'pinyin': 'bāng máng', 'definition': 'help'},
    {'character': '包', 'pinyin': 'bāo', 'definition': 'package'},
    {'character': '包子', 'pinyin': 'bāo zi', 'definition': 'bun'},
    {'character': '杯', 'pinyin': 'bēi', 'definition': 'cup'},
    {'character': '杯子', 'pinyin': 'bēi zi', 'definition': 'cup'},
    {'character': '北', 'pinyin': 'běi', 'definition': 'north'},
    {'character': '北边', 'pinyin': 'běi biān  North', 'definition': 'side'},
    {'character': '北京', 'pinyin': 'běi jīng', 'definition': 'Beijing'},
    {'character': '本（量）', 'pinyin': 'běn', 'definition': '(measure  word for books or volumes)'},
    {'character': '本子', 'pinyin': 'běn zi', 'definition': 'book'},
    {'character': '比', 'pinyin': 'bǐ particle used for', 'definition': 'comparison'},
    {'character': '别（副）', 'pinyin': 'bié', 'definition': 'Don\'t'},
    {'character': '别的', 'pinyin': 'bié de', 'definition': 'other'},
    {'character': '病', 'pinyin': 'bìng', 'definition': 'disease'},
    {'character': '病人', 'pinyin': 'bìng rén', 'definition': 'patient'},
    {'character': '不大', 'pinyin': 'bú dà not', 'definition': 'big'},
    {'character': '不对', 'pinyin': 'bú duì', 'definition': 'wrong'},
    {'character': '不客气', 'pinyin': 'bú kè qì', 'definition': 'You\'re welcome'},
    {'character': '不用', 'pinyin': 'bú yòng  No need', 'definition': 'to'},
    {'character': '不', 'pinyin': 'bù', 'definition': 'No'},
    {'character': '菜', 'pinyin': 'cài', 'definition': 'dish'},
    {'character': '茶', 'pinyin': 'chá', 'definition': 'tea'},
    {'character': '差', 'pinyin': 'chà differ', 'definition': 'from; bad; short of'},
    {'character': '常', 'pinyin': 'cháng', 'definition': 'often'},
    {'character': '常常', 'pinyin': 'cháng cháng', 'definition': 'often'},
    {'character': '唱', 'pinyin': 'chàng', 'definition': 'sing'},
    {'character': '唱歌', 'pinyin': 'chàng gē', 'definition': 'sing'},
    {'character': '车', 'pinyin': 'chē', 'definition': 'car'},
    {'character': '车票', 'pinyin': 'chē piào', 'definition': 'ticket'},
    {'character': '车上', 'pinyin': 'chē shàng  in the', 'definition': 'car'},
    {'character': '车站', 'pinyin': 'chē zhàn', 'definition': 'station'},
    {'character': '吃', 'pinyin': 'chī', 'definition': 'eat'},
    {'character': '吃饭', 'pinyin': 'chī fàn  have', 'definition': 'meal'},
    {'character': '出', 'pinyin': 'chū', 'definition': 'out'},
    {'character': '出来', 'pinyin': 'chū lái', 'definition': 'come'},
    {'character': '出去', 'pinyin': 'chū qù  go', 'definition': 'out'},
    {'character': '穿', 'pinyin': 'chuān', 'definition': 'wear'},
    {'character': '床', 'pinyin': 'chuáng', 'definition': 'bed'},
    {'character': '次（量）', 'pinyin': 'cì', 'definition': '(measure word for times, frequency)'},
    {'character': '从', 'pinyin': 'cóng', 'definition': 'from'},
    {'character': '错', 'pinyin': 'cuò', 'definition': 'wrong'},
    {'character': '打（动）', 'pinyin': 'dǎ', 'definition': 'hit, take'},
    {'character': '打车', 'pinyin': 'dǎ chē take a', 'definition': 'taxi'},
    {'character': '打电话', 'pinyin': 'dǎ diàn huà  make a', 'definition': 'phonecall'},
    {'character': '打开', 'pinyin': 'dǎ kāi turn', 'definition': 'on'},
    {'character': '打球', 'pinyin': 'dǎ qiú play', 'definition': 'ball'},
    {'character': '大', 'pinyin': 'dà', 'definition': 'large, big'},
    {'character': '大学', 'pinyin': 'dà xué', 'definition': 'university'},
    {'character': '大学生', 'pinyin': 'dà xué shēng  university', 'definition': 'student'},
    {'character': '到', 'pinyin': 'dào', 'definition': 'reach'},
    {'character': '得到', 'pinyin': 'dé dào', 'definition': 'get'},
    {'character': '地', 'pinyin': 'de auxiliary', 'definition': 'word'},
    {'character': '的', 'pinyin': 'de', 'definition': '(aux.)'},
    {'character': '等（动）', 'pinyin': 'děng', 'definition': 'wait'},
    {'character': '地', 'pinyin': 'dì', 'definition': 'ground'},
    {'character': '地点', 'pinyin': 'dìdiǎn', 'definition': 'location'},
    {'character': '地方', 'pinyin': 'dìfang', 'definition': 'local'},
    {'character': '地上', 'pinyin': 'dì shàng  on the', 'definition': 'ground'},
    {'character': '地图', 'pinyin': 'dìtú', 'definition': 'Map'},
    {'character': '弟弟｜弟', 'pinyin': 'dì di', 'definition': 'younger brother'},
    {'character': '第（第二）', 'pinyin': 'dì', 'definition': '（ dì èr ） auxiliary word for ordinal numbers'},
    {'character': '点', 'pinyin': 'diǎn', 'definition': 'spot'},
    {'character': '电', 'pinyin': 'diàn', 'definition': 'electricity'},
    {'character': '电话', 'pinyin': 'diàn huà', 'definition': 'phone'},
    {'character': '电脑', 'pinyin': 'diànnǎo', 'definition': 'Computer'},
    {'character': '电视', 'pinyin': 'diànshì', 'definition': 'television'},
    {'character': '电视机', 'pinyin': 'diàn shì jī', 'definition': 'television'},
    {'character': '电影', 'pinyin': 'diànyǐng', 'definition': 'Film'},
    {'character': '电影院', 'pinyin': 'diàn', 'definition': 'yǐng'},
    {'character': '东', 'pinyin': 'dōng', 'definition': 'east'},
    {'character': '东边', 'pinyin': 'dōng biān  east', 'definition': 'side'},
    {'character': '东西', 'pinyin': 'dōngxi', 'definition': 'thing'},
    {'character': '动', 'pinyin': 'dòng', 'definition': 'move'},
    {'character': '动作', 'pinyin': 'dòngzuò', 'definition': 'action'},
    {'character': '都', 'pinyin': 'dōu', 'definition': 'all'},
    {'character': '读', 'pinyin': 'dú', 'definition': 'read'},
    {'character': '读书', 'pinyin': 'dú shū', 'definition': 'reading; study'},
    {'character': '对（形）', 'pinyin': 'duì', 'definition': 'right'},
    {'character': '对不起', 'pinyin': 'duìbuqǐ', 'definition': 'sorry.'},
    {'character': '多少', 'pinyin': 'duōshao  how', 'definition': 'much'},
    {'character': '饿', 'pinyin': 'è', 'definition': 'hungry'},
    {'character': '儿子', 'pinyin': 'érzi', 'definition': 'Son'},
    {'character': '二', 'pinyin': 'èr', 'definition': 'Two'},
    {'character': '饭', 'pinyin': 'fàn', 'definition': 'rice; meal'},
    {'character': '饭店', 'pinyin': 'fàndiàn', 'definition': 'restaurant'},
    {'character': '房间', 'pinyin': 'fángjiān', 'definition': 'Room'},
    {'character': '房子', 'pinyin': 'fáng zi', 'definition': 'house; building'},
    {'character': '放', 'pinyin': 'fàng', 'definition': 'discharge'},
    {'character': '放假', 'pinyin': 'fàng jià', 'definition': 'holiday; have a holiday'},
    {'character': '放学', 'pinyin': 'fàng xué  off', 'definition': 'school'},
    {'character': '飞', 'pinyin': 'fēi', 'definition': 'fly'},
    {'character': '飞机', 'pinyin': 'fēijī', 'definition': 'aircraft'},
    {'character': '非常', 'pinyin': 'fēicháng', 'definition': 'very'},
    {'character': '风', 'pinyin': 'fēng', 'definition': 'wind'},
    {'character': '干', 'pinyin': 'gān', 'definition': 'dry'},
    {'character': '干净', 'pinyin': 'gānjìng', 'definition': 'clean'},
    {'character': '干', 'pinyin': 'gàn', 'definition': 'do'},
    {'character': '干什么', 'pinyin': 'gàn shén me What to', 'definition': 'do'},
    {'character': '高', 'pinyin': 'gāo', 'definition': 'high'},
    {'character': '高兴', 'pinyin': 'gāoxìng', 'definition': 'happy'},
    {'character': '告诉', 'pinyin': 'gàosu', 'definition': 'tell'},
    {'character': '哥哥｜哥', 'pinyin': 'gē ge', 'definition': 'gē elder brother'},
    {'character': '歌', 'pinyin': 'gē', 'definition': 'song'},
    {'character': '个', 'pinyin': 'gè', 'definition': 'individual'},
    {'character': '给', 'pinyin': 'gěi', 'definition': 'give'},
    {'character': '跟', 'pinyin': 'gēn', 'definition': 'with'},
    {'character': '工人', 'pinyin': 'gōngrén', 'definition': 'Worker'},
    {'character': '工作', 'pinyin': 'gōngzuò', 'definition': 'work'},
    {'character': '关（动）', 'pinyin': 'guān', 'definition': 'shut; close; turn off'},
    {'character': '关上', 'pinyin': 'guān  shàng', 'definition': 'close;shut to; turn off'},
    {'character': '贵', 'pinyin': 'guì', 'definition': 'noble'},
    {'character': '国', 'pinyin': 'guó', 'definition': 'country; state; nation'},
    {'character': '国家', 'pinyin': 'guójiā', 'definition': 'Country'},
    {'character': '国外', 'pinyin': 'guó wài', 'definition': 'foreign; oversea; abroad'},
    {'character': '过', 'pinyin': 'guò', 'definition': 'pass'},
    {'character': '还', 'pinyin': 'hái', 'definition': 'also; still; yet'},
    {'character': '还是', 'pinyin': 'háishi', 'definition': 'still'},
    {'character': '还有', 'pinyin': 'hái yǒu', 'definition': 'also; in addition; besides'},
    {'character': '孩子', 'pinyin': 'háizi', 'definition': 'Children'},
    {'character': '汉语', 'pinyin': 'hànyǔ', 'definition': 'Chinese'},
    {'character': '汉字', 'pinyin': 'hàn zì  Chinese', 'definition': 'character'},
    {'character': '好（形）', 'pinyin': 'hǎo', 'definition': 'good'},
    {'character': '好吃', 'pinyin': 'hǎochī', 'definition': 'Yummy'},
    {'character': '好看', 'pinyin': 'hǎo kàn good', 'definition': 'looking'},
    {'character': '好听', 'pinyin': 'hǎo tīng pleasant to', 'definition': 'hear'},
    {'character': '好玩儿', 'pinyin': 'hǎo wánr', 'definition': 'fun; interesting'},
    {'character': '号', 'pinyin': 'hào', 'definition': 'Number/date'},
    {'character': '喝', 'pinyin': 'hē', 'definition': 'drink'},
    {'character': '和', 'pinyin': 'hé', 'definition': 'and'},
    {'character': '很', 'pinyin': 'hěn', 'definition': 'very'},
    {'character': '后', 'pinyin': 'hòu', 'definition': 'back;  behind; after; later'},
    {'character': '后边', 'pinyin': 'hòu biān', 'definition': 'behind; back'},
    {'character': '后天', 'pinyin': 'hòu tiān  day after', 'definition': 'tomorrow'},
    {'character': '花（名）', 'pinyin': 'huā', 'definition': 'flower'},
    {'character': '话', 'pinyin': 'huà', 'definition': 'word; words'},
    {'character': '坏', 'pinyin': 'huài', 'definition': 'bad'},
    {'character': '还', 'pinyin': 'huán', 'definition': 'return; pay back'},
    {'character': '回（动）', 'pinyin': 'huí go', 'definition': 'back; return'},
    {'character': '回答', 'pinyin': 'huídá', 'definition': 'Answer'},
    {'character': '回到', 'pinyin': 'huí dào  back', 'definition': 'to'},
    {'character': '回家', 'pinyin': 'huí jiā go', 'definition': 'home; return home'},
    {'character': '回来', 'pinyin': 'huí lái  come', 'definition': 'back; return'},
    {'character': '回去', 'pinyin': 'huí qù  go', 'definition': 'back'},
    {'character': '会（动）', 'pinyin': 'huì', 'definition': 'can; be able to'},
    {'character': '火车', 'pinyin': 'huǒ chē', 'definition': 'train'},
    {'character': '机场', 'pinyin': 'jīchǎng', 'definition': 'Airport'},
    {'character': '机票', 'pinyin': 'jī piào  air', 'definition': 'ticket'},
    {'character': '鸡蛋', 'pinyin': 'jīdàn', 'definition': 'Egg'},
    {'character': '几', 'pinyin': 'jǐ', 'definition': 'several'},
    {'character': '记', 'pinyin': 'jì', 'definition': 'remember'},
    {'character': '记得', 'pinyin': 'jìdé', 'definition': 'remember'},
    {'character': '记住', 'pinyin': 'jì zhù', 'definition': 'remember; keep in mind'},
    {'character': '家', 'pinyin': 'jiā', 'definition': 'home'},
    {'character': '家里', 'pinyin': 'jiā lǐ In the', 'definition': 'home'},
    {'character': '家人', 'pinyin': 'jiā rén', 'definition': 'family'},
    {'character': '间', 'pinyin': 'jiān', 'definition': 'between; measure word for rooms'},
    {'character': '见', 'pinyin': 'jiàn', 'definition': 'see; meet'},
    {'character': '见面', 'pinyin': 'jiànmiàn', 'definition': 'meet'},
    {'character': '教', 'pinyin': 'jiāo', 'definition': 'teach'},
    {'character': '叫（动）', 'pinyin': 'jiào', 'definition': 'call; be called'},
    {'character': '教学楼', 'pinyin': 'jiào xué lóu  teaching', 'definition': 'building'},
    {'character': '姐姐｜姐', 'pinyin': 'jiě jie', 'definition': 'elder sister'},
    {'character': '介绍', 'pinyin': 'jièshào', 'definition': 'introduce'},
    {'character': '今年', 'pinyin': 'jīn nián  this', 'definition': 'year'},
    {'character': '今天', 'pinyin': 'jīntiān', 'definition': 'Today'},
    {'character': '进', 'pinyin': 'jìn', 'definition': 'enter'},
    {'character': '进来', 'pinyin': 'jìn lái  come', 'definition': 'in'},
    {'character': '进去', 'pinyin': 'jìn qù  go', 'definition': 'in'},
    {'character': '九', 'pinyin': 'jiǔ', 'definition': 'Nine'},
    {'character': '就', 'pinyin': 'jiù as soon', 'definition': 'as; right away; then'},
    {'character': '觉得', 'pinyin': 'juéde', 'definition': 'Think'},
    {'character': '开', 'pinyin': 'kāi', 'definition': 'open'},
    {'character': '开车', 'pinyin': 'kāi chē', 'definition': 'drive; drive a car'},
    {'character': '开会', 'pinyin': 'kāi huì have a', 'definition': 'meeting'},
    {'character': '开玩笑', 'pinyin': 'kāiwánxiào  Make fun', 'definition': 'of'},
    {'character': '看', 'pinyin': 'kàn', 'definition': 'see'},
    {'character': '看病', 'pinyin': 'kàn bìng see a', 'definition': 'doctor'},
    {'character': '看到', 'pinyin': 'kàn dào', 'definition': 'see'},
    {'character': '看见', 'pinyin': 'kànjiàn', 'definition': 'seeing'},
    {'character': '考', 'pinyin': 'kǎo', 'definition': 'test; examine'},
    {'character': '考试', 'pinyin': 'kǎoshì', 'definition': 'Examination'},
    {'character': '渴', 'pinyin': 'kě', 'definition': 'thirsty'},
    {'character': '课', 'pinyin': 'kè', 'definition': 'course'},
    {'character': '课本', 'pinyin': 'kè běn', 'definition': 'textbook'},
    {'character': '课文', 'pinyin': 'kè wén', 'definition': 'text'},
    {'character': '口', 'pinyin': 'kǒu', 'definition': 'mouth'},
    {'character': '块', 'pinyin': 'kuài', 'definition': 'block'},
    {'character': '快', 'pinyin': 'kuài', 'definition': 'fast'},
    {'character': '来', 'pinyin': 'lái', 'definition': 'come'},
    {'character': '来到', 'pinyin': 'lái dào', 'definition': 'come; arrive'},
    {'character': '老（形）', 'pinyin': 'lǎo', 'definition': 'old; aged'},
    {'character': '老人', 'pinyin': 'lǎo rén  old', 'definition': 'people; the aged'},
    {'character': '老师', 'pinyin': 'lǎoshī', 'definition': 'Teacher'},
    {'character': '了', 'pinyin': 'le past tense', 'definition': 'marker'},
    {'character': '累', 'pinyin': 'lèi', 'definition': 'tired'},
    {'character': '冷', 'pinyin': 'lěng', 'definition': 'cold'},
    {'character': '里', 'pinyin': 'lǐ', 'definition': 'in'},
    {'character': '里边', 'pinyin': 'lǐ biān', 'definition': 'inside'},
    {'character': '两（数）', 'pinyin': 'liǎng', 'definition': 'two'},
    {'character': '六', 'pinyin': 'liù', 'definition': 'Six'},
    {'character': '楼', 'pinyin': 'lóu', 'definition': 'floor'},
    {'character': '楼上', 'pinyin': 'lóu shàng', 'definition': 'upstairs'},
    {'character': '楼下', 'pinyin': 'lóu xià', 'definition': 'downstairs'},
    {'character': '路', 'pinyin': 'lù', 'definition': 'road'},
    {'character': '路口', 'pinyin': 'lù kǒu', 'definition': 'intersection; crossing'},
    {'character': '路上', 'pinyin': 'lù shàng  on the', 'definition': 'road'},
    {'character': '妈妈｜妈', 'pinyin': 'mā ma', 'definition': 'mother'},
    {'character': '马路', 'pinyin': 'mǎ lù', 'definition': 'road; street'},
    {'character': '马上', 'pinyin': 'mǎshàng  Right', 'definition': 'off'},
    {'character': '吗', 'pinyin': 'ma auxiliary', 'definition': 'word'},
    {'character': '买', 'pinyin': 'mǎi', 'definition': 'buy'},
    {'character': '慢', 'pinyin': 'màn', 'definition': 'slow'},
    {'character': '忙', 'pinyin': 'máng', 'definition': 'busy'},
    {'character': '毛（量）', 'pinyin': 'máo a fractional unit of money in', 'definition': 'China'},
    {'character': '没', 'pinyin': 'méi', 'definition': 'no'},
    {'character': '没关系', 'pinyin': 'méiguānxi  No', 'definition': 'problem'},
    {'character': '没什么', 'pinyin': 'méi shén me', 'definition': 'It\'s nothing'},
    {'character': '没事儿', 'pinyin': 'méi shìr', 'definition': 'It\'s okay'},
    {'character': '没有', 'pinyin': 'méi yǒu have', 'definition': 'not; no'},
    {'character': '妹妹｜妹', 'pinyin': 'mèi mei', 'definition': 'sister'},
    {'character': '门', 'pinyin': 'mén', 'definition': 'door'},
    {'character': '门口', 'pinyin': 'mén kǒu', 'definition': 'doorway'},
    {'character': '门票', 'pinyin': 'mén piào', 'definition': 'tickets'},
    {'character': '们（朋友们）', 'pinyin': 'men', 'definition': 'us'},
    {'character': '米饭', 'pinyin': 'mǐfàn  Steamed', 'definition': 'Rice'},
    {'character': '面包', 'pinyin': 'miànbāo', 'definition': 'Bread'},
    {'character': '面条儿', 'pinyin': 'miàn tiáor', 'definition': 'noodles'},
    {'character': '名字', 'pinyin': 'míngzi', 'definition': 'Name'},
    {'character': '明白', 'pinyin': 'míngbai', 'definition': 'clear'},
    {'character': '明年', 'pinyin': 'míng nián  next', 'definition': 'year'},
    {'character': '明天', 'pinyin': 'míngtiān', 'definition': 'Tomorrow'},
    {'character': '拿', 'pinyin': 'ná', 'definition': 'take'},
    {'character': '哪', 'pinyin': 'nǎ', 'definition': 'which'},
    {'character': '哪里', 'pinyin': 'nǎ lǐ', 'definition': 'where'},
    {'character': '哪儿', 'pinyin': 'nǎr', 'definition': 'where'},
    {'character': '哪些', 'pinyin': 'nǎ xiē', 'definition': 'which'},
    {'character': '那（代）', 'pinyin': 'nà', 'definition': 'that'},
    {'character': '那边', 'pinyin': 'nà biān', 'definition': 'there'},
    {'character': '那里', 'pinyin': 'nà lǐ', 'definition': 'there'},
    {'character': '那儿', 'pinyin': 'nàr', 'definition': 'there'},
    {'character': '那些', 'pinyin': 'nà xiē', 'definition': 'those'},
    {'character': '奶', 'pinyin': 'nǎi', 'definition': 'milk'},
    {'character': '奶奶', 'pinyin': 'nǎinai', 'definition': 'grandma'},
    {'character': '男', 'pinyin': 'nán', 'definition': 'Man'},
    {'character': '男孩儿', 'pinyin': 'nán háir', 'definition': 'boy'},
    {'character': '男朋友', 'pinyin': 'nán péng yǒu', 'definition': 'boyfriend'},
    {'character': '男人', 'pinyin': 'nán ren', 'definition': 'man'},
    {'character': '男生', 'pinyin': 'nán shēng', 'definition': 'boy'},
    {'character': '南', 'pinyin': 'nán', 'definition': 'south'},
    {'character': '南边', 'pinyin': 'nán biān', 'definition': 'south;  south side'},
    {'character': '难', 'pinyin': 'nán', 'definition': 'hard, difficult'},
    {'character': '呢', 'pinyin': 'ne auxiliary', 'definition': 'word'},
    {'character': '能', 'pinyin': 'néng', 'definition': 'can'},
    {'character': '你', 'pinyin': 'nǐ', 'definition': 'you'},
    {'character': '你们', 'pinyin': 'nǐ men', 'definition': 'you'},
    {'character': '年', 'pinyin': 'nián', 'definition': 'year'},
    {'character': '您', 'pinyin': 'nín', 'definition': 'you'},
    {'character': '牛奶', 'pinyin': 'niúnǎi', 'definition': 'milk'},
    {'character': '女', 'pinyin': 'nǚ', 'definition': 'woman'},
    {'character': '女孩儿', 'pinyin': 'nǚ háir', 'definition': 'girl'},
    {'character': '女朋友', 'pinyin': 'nǚ péng yǒu', 'definition': 'girlfriend'},
    {'character': '女人', 'pinyin': 'nǚ ren', 'definition': 'woman'},
    {'character': '女生', 'pinyin': 'nǚ shēng', 'definition': 'girl'},
    {'character': '旁边', 'pinyin': 'pángbiān', 'definition': 'Side'},
    {'character': '跑', 'pinyin': 'pǎo', 'definition': 'run'},
    {'character': '朋友', 'pinyin': 'péngyou', 'definition': 'Friend'},
    {'character': '票', 'pinyin': 'piào', 'definition': 'ticket'},
    {'character': '七', 'pinyin': 'qī', 'definition': 'Seven'},
    {'character': '起', 'pinyin': 'qǐ get', 'definition': 'up; start; rise'},
    {'character': '起床', 'pinyin': 'qǐchuáng  Get', 'definition': 'up'},
    {'character': '起来', 'pinyin': 'qǐlái get', 'definition': 'up'},
    {'character': '汽车', 'pinyin': 'qì chē', 'definition': 'car'},
    {'character': '前', 'pinyin': 'qián', 'definition': 'front'},
    {'character': '前边', 'pinyin': 'qián biān  in', 'definition': 'front'},
    {'character': '前天', 'pinyin': 'qián tiān  the day before', 'definition': 'yesterday'},
    {'character': '钱', 'pinyin': 'qián', 'definition': 'money'},
    {'character': '钱包', 'pinyin': 'qián bāo', 'definition': 'wallet'},
    {'character': '请', 'pinyin': 'qǐng', 'definition': 'please'},
    {'character': '请假', 'pinyin': 'qǐngjià  ask for', 'definition': 'leave'},
    {'character': '请进', 'pinyin': 'qǐng jìn  please come', 'definition': 'in'},
    {'character': '请问', 'pinyin': 'qǐng wèn  excuse', 'definition': 'me'},
    {'character': '请坐', 'pinyin': 'qǐng zuò  please have a', 'definition': 'seat'},
    {'character': '球', 'pinyin': 'qiú', 'definition': 'ball'},
    {'character': '去', 'pinyin': 'qù', 'definition': 'go'},
    {'character': '去年', 'pinyin': 'qùnián  Last', 'definition': 'year'},
    {'character': '热', 'pinyin': 'rè', 'definition': 'heat'},
    {'character': '人', 'pinyin': 'rén', 'definition': 'people'},
    {'character': '认识', 'pinyin': 'rènshi', 'definition': 'know'},
    {'character': '认真', 'pinyin': 'rènzhēn', 'definition': 'earnest'},
    {'character': '日', 'pinyin': 'rì', 'definition': 'date'},
    {'character': '日期', 'pinyin': 'rìqī', 'definition': 'Date'},
    {'character': '肉', 'pinyin': 'ròu', 'definition': 'meat'},
    {'character': '三', 'pinyin': 'sān', 'definition': 'Three'},
    {'character': '山', 'pinyin': 'shān', 'definition': 'mountain'},
    {'character': '商场', 'pinyin': 'shāng  chǎng', 'definition': 'mall; shopping mall'},
    {'character': '商店', 'pinyin': 'shāngdiàn', 'definition': 'Shop'},
    {'character': '上', 'pinyin': 'shàng', 'definition': 'upper'},
    {'character': '上班', 'pinyin': 'shàngbān  go to', 'definition': 'work'},
    {'character': '上边', 'pinyin': 'shàng  biān', 'definition': 'above; on'},
    {'character': '上车', 'pinyin': 'shàng  chē get', 'definition': 'on'},
    {'character': '上次', 'pinyin': 'shàng  cì last', 'definition': 'time'},
    {'character': '上课', 'pinyin': 'shàng  kè attend', 'definition': 'class; have a class'},
    {'character': '上网', 'pinyin': 'shàngwǎng  Surf the', 'definition': 'Internet'},
    {'character': '上午', 'pinyin': 'shàngwǔ', 'definition': 'morning'},
    {'character': '上学', 'pinyin': 'shàng  xué go to', 'definition': 'school'},
    {'character': '少', 'pinyin': 'shǎo', 'definition': 'less'},
    {'character': '谁', 'pinyin': 'shéi', 'definition': 'who'},
    {'character': '身上', 'pinyin': 'shēn shàng', 'definition': 'body; on body'},
    {'character': '身体', 'pinyin': 'shēntǐ', 'definition': 'body'},
    {'character': '什么', 'pinyin': 'shénme', 'definition': 'What'},
    {'character': '生病', 'pinyin': 'shēngbìng  Fall', 'definition': 'ill'},
    {'character': '生气', 'pinyin': 'shēngqì  get', 'definition': 'angry'},
    {'character': '生日', 'pinyin': 'shēngrì', 'definition': 'Birthday'},
    {'character': '十', 'pinyin': 'shí', 'definition': 'Ten'},
    {'character': '时候', 'pinyin': 'shíhou', 'definition': 'time'},
    {'character': '时间', 'pinyin': 'shíjiān', 'definition': 'time'},
    {'character': '事', 'pinyin': 'shì', 'definition': 'thing'},
    {'character': '试', 'pinyin': 'shì', 'definition': 'try'},
    {'character': '是', 'pinyin': 'shì', 'definition': 'yes'},
    {'character': '是不是', 'pinyin': 'shì bú shì', 'definition': 'isn\'t it?'},
    {'character': '手', 'pinyin': 'shǒu', 'definition': 'hand'},
    {'character': '手机', 'pinyin': 'shǒujī  Mobile', 'definition': 'phone'},
    {'character': '书', 'pinyin': 'shū', 'definition': 'book'},
    {'character': '书包', 'pinyin': 'shū bāo  school', 'definition': 'bag'},
    {'character': '书店', 'pinyin': 'shū diàn', 'definition': 'bookstore'},
    {'character': '树', 'pinyin': 'shù', 'definition': 'tree'},
    {'character': '水', 'pinyin': 'shuǐ', 'definition': 'water'},
    {'character': '水果', 'pinyin': 'shuǐguǒ', 'definition': 'Fruits'},
    {'character': '睡', 'pinyin': 'shuì', 'definition': 'sleep'},
    {'character': '睡觉', 'pinyin': 'shuìjiào', 'definition': 'sleep'},
    {'character': '说', 'pinyin': 'shuō', 'definition': 'speak'},
    {'character': '说话', 'pinyin': 'shuōhuà', 'definition': 'talk'},
    {'character': '四', 'pinyin': 'sì', 'definition': 'Four'},
    {'character': '送', 'pinyin': 'sòng', 'definition': 'give'},
    {'character': '岁', 'pinyin': 'suì', 'definition': 'year, age'},
    {'character': '他', 'pinyin': 'tā', 'definition': 'he'},
    {'character': '他们', 'pinyin': 'tā men', 'definition': 'they'},
    {'character': '她', 'pinyin': 'tā', 'definition': 'she'},
    {'character': '她们', 'pinyin': 'tā men', 'definition': 'they'},
    {'character': '太', 'pinyin': 'tài', 'definition': 'too'},
    {'character': '天', 'pinyin': 'tiān', 'definition': 'day'},
    {'character': '天气', 'pinyin': 'tiānqì', 'definition': 'weather'},
    {'character': '听', 'pinyin': 'tīng', 'definition': 'hear'},
    {'character': '听到', 'pinyin': 'tīng dào', 'definition': 'hear'},
    {'character': '听见', 'pinyin': 'tīng jiàn', 'definition': 'hear'},
    {'character': '听写', 'pinyin': 'tīng xiě', 'definition': 'dictation; dictate'},
    {'character': '同学', 'pinyin': 'tóngxué', 'definition': 'Classmate'},
    {'character': '图书馆', 'pinyin': 'túshūguǎn', 'definition': 'Library'},
    {'character': '外', 'pinyin': 'wài', 'definition': 'abroad, outside'},
    {'character': '外边', 'pinyin': 'wài biān', 'definition': 'outside'},
    {'character': '外国', 'pinyin': 'wài guó  foreign', 'definition': 'country'},
    {'character': '外语', 'pinyin': 'wài yǔ foreign', 'definition': 'language'},
    {'character': '玩儿', 'pinyin': 'wánr', 'definition': 'play'},
    {'character': '晚', 'pinyin': 'wǎn', 'definition': 'late'},
    {'character': '晚饭', 'pinyin': 'wǎn fàn', 'definition': 'dinner'},
    {'character': '晚上', 'pinyin': 'wǎnshang', 'definition': 'Night'},
    {'character': '网上', 'pinyin': 'wǎng  shàng', 'definition': 'online'},
    {'character': '网友', 'pinyin': 'wǎng yǒu  net', 'definition': 'friend'},
    {'character': '忘', 'pinyin': 'wàng', 'definition': 'forget'},
    {'character': '忘记', 'pinyin': 'wàngjì', 'definition': 'forget'},
    {'character': '问', 'pinyin': 'wèn', 'definition': 'ask'},
    {'character': '我', 'pinyin': 'wǒ', 'definition': 'I'},
    {'character': '我们', 'pinyin': 'wǒmen', 'definition': 'We'},
    {'character': '五', 'pinyin': 'wǔ', 'definition': 'Five'},
    {'character': '午饭', 'pinyin': 'wǔ fàn', 'definition': 'lunch'},
    {'character': '西', 'pinyin': 'xī', 'definition': 'west'},
    {'character': '西边', 'pinyin': 'xī biān', 'definition': 'west; west side'},
    {'character': '洗', 'pinyin': 'xǐ', 'definition': 'wash'},
    {'character': '洗手间', 'pinyin': 'xǐshǒujiān', 'definition': 'Restroom'},
    {'character': '喜欢', 'pinyin': 'xǐhuan', 'definition': 'like'},
    {'character': '下班', 'pinyin': 'xià bān  get off', 'definition': 'work'},
    {'character': '下边', 'pinyin': 'xià biān', 'definition': 'below; under'},
    {'character': '下车', 'pinyin': 'xià chē get', 'definition': 'off'},
    {'character': '下次', 'pinyin': 'xià cì  next', 'definition': 'time'},
    {'character': '下课', 'pinyin': 'xià kè  finish', 'definition': 'class'},
    {'character': '下午', 'pinyin': 'xiàwǔ', 'definition': 'Afternoon'},
    {'character': '下雨', 'pinyin': 'xiàyǔ', 'definition': 'rain'},
    {'character': '先', 'pinyin': 'xiān', 'definition': 'before'},
    {'character': '先生', 'pinyin': 'xiānsheng', 'definition': 'Sir'},
    {'character': '现在', 'pinyin': 'xiànzài', 'definition': 'Now'},
    {'character': '想', 'pinyin': 'xiǎng', 'definition': 'think'},
    {'character': '小', 'pinyin': 'xiǎo', 'definition': 'Small'},
    {'character': '小孩儿', 'pinyin': 'xiǎo háir', 'definition': 'child; kid'},
    {'character': '小姐', 'pinyin': 'xiǎojiě', 'definition': 'Miss'},
    {'character': '小朋友', 'pinyin': 'xiǎo péng yǒu', 'definition': 'child; kid'},
    {'character': '小时', 'pinyin': 'xiǎoshí', 'definition': 'hour'},
    {'character': '小学', 'pinyin': 'xiǎo xué  primary', 'definition': 'school; elementary schoo'},
    {'character': '小学生', 'pinyin': 'xiǎo', 'definition': 'xué'},
    {'character': '笑', 'pinyin': 'xiào', 'definition': 'laugh'},
    {'character': '写', 'pinyin': 'xiě', 'definition': 'write'},
    {'character': '谢谢', 'pinyin': 'xièxie  Thank', 'definition': 'you'},
    {'character': '新', 'pinyin': 'xīn', 'definition': 'new'},
    {'character': '新年', 'pinyin': 'xīn nián  New', 'definition': 'Year'},
    {'character': '星期', 'pinyin': 'xīngqī', 'definition': 'week'},
    {'character': '星期日', 'pinyin': 'xīng qī rì', 'definition': 'Sunday'},
    {'character': '星期天', 'pinyin': 'xīng qī tiān', 'definition': 'Sunday'},
    {'character': '行', 'pinyin': 'xíng', 'definition': 'That\'s ok'},
    {'character': '休息', 'pinyin': 'xiūxi', 'definition': 'Rest'},
    {'character': '学', 'pinyin': 'xué', 'definition': 'learn; study'},
    {'character': '学生', 'pinyin': 'xuésheng', 'definition': 'Student'},
    {'character': '学习', 'pinyin': 'xuéxí', 'definition': 'Study'},
    {'character': '学校', 'pinyin': 'xuéxiào', 'definition': 'School'},
    {'character': '学院', 'pinyin': 'xué yuàn', 'definition': 'college; academy'},
    {'character': '要（动）', 'pinyin': 'yào', 'definition': 'want'},
    {'character': '爷爷', 'pinyin': 'yéye', 'definition': 'grandpa'},
    {'character': '也', 'pinyin': 'yě', 'definition': 'also'},
    {'character': '页', 'pinyin': 'yè', 'definition': 'page'},
    {'character': '一', 'pinyin': 'yī', 'definition': 'One'},
    {'character': '衣服', 'pinyin': 'yīfu', 'definition': 'clothes'},
    {'character': '医生', 'pinyin': 'yīshēng', 'definition': 'Doctor'},
    {'character': '医院', 'pinyin': 'yīyuàn', 'definition': 'Hospital'},
    {'character': '一半', 'pinyin': 'yí bàn', 'definition': 'half'},
    {'character': '一会儿', 'pinyin': 'yíhuìr  A little', 'definition': 'while'},
    {'character': '一块儿', 'pinyin': 'yí kuàir', 'definition': 'together'},
    {'character': '一下儿', 'pinyin': 'yí xiàr  a little', 'definition': 'bit'},
    {'character': '一样', 'pinyin': 'yíyàng', 'definition': 'equally'},
    {'character': '一边', 'pinyin': 'yìbiān  One', 'definition': 'side'},
    {'character': '一点儿', 'pinyin': 'yīdiǎnr  a little', 'definition': 'bit'},
    {'character': '一起', 'pinyin': 'yìqǐ', 'definition': 'together'},
    {'character': '一些', 'pinyin': 'yì xiē', 'definition': 'some'},
    {'character': '用', 'pinyin': 'yòng', 'definition': 'use'},
    {'character': '有', 'pinyin': 'yǒu', 'definition': 'have'},
    {'character': '有的', 'pinyin': 'yǒu de', 'definition': 'some'},
    {'character': '有名', 'pinyin': 'yǒumíng', 'definition': 'Famous'},
    {'character': '有时候｜有时', 'pinyin': 'yǒu', 'definition': 'shí'},
    {'character': '有（一）些', 'pinyin': 'yǒu', 'definition': 'have'},
    {'character': '有用', 'pinyin': 'yǒu yòng', 'definition': 'useful'},
    {'character': '右', 'pinyin': 'yòu', 'definition': 'right'},
    {'character': '右边', 'pinyin': 'yòubian', 'definition': 'Right'},
    {'character': '雨', 'pinyin': 'yǔ', 'definition': 'rain'},
    {'character': '元', 'pinyin': 'yuán', 'definition': 'element; Yuan'},
    {'character': '远', 'pinyin': 'yuǎn', 'definition': 'far'},
    {'character': '月', 'pinyin': 'yuè', 'definition': 'month'},
    {'character': '再', 'pinyin': 'zài', 'definition': 'again'},
    {'character': '再见', 'pinyin': 'zàijiàn', 'definition': 'Bye'},
    {'character': '在', 'pinyin': 'zài', 'definition': 'stay; in process of'},
    {'character': '在家', 'pinyin': 'zài jiā at', 'definition': 'home'},
    {'character': '早', 'pinyin': 'zǎo', 'definition': 'early'},
    {'character': '早饭', 'pinyin': 'zǎo fàn', 'definition': 'breakfast'},
    {'character': '早上', 'pinyin': 'zǎoshang', 'definition': 'Morning'},
    {'character': '怎么', 'pinyin': 'zěnme', 'definition': 'How'},
    {'character': '站（名）', 'pinyin': 'zhàn', 'definition': 'station'},
    {'character': '找', 'pinyin': 'zhǎo  look', 'definition': 'for'},
    {'character': '找到', 'pinyin': 'zhǎo dào', 'definition': 'find'},
    {'character': '这', 'pinyin': 'zhè Here', 'definition': '(here)'},
    {'character': '这边', 'pinyin': 'zhè biān', 'definition': 'here'},
    {'character': '这里', 'pinyin': 'zhè lǐ', 'definition': 'here'},
    {'character': '这儿', 'pinyin': 'zhèr', 'definition': 'here'},
    {'character': '这些', 'pinyin': 'zhè xiē', 'definition': 'these'},
    {'character': '着', 'pinyin': 'zhe in process', 'definition': 'of'},
    {'character': '真', 'pinyin': 'zhēn', 'definition': 'really'},
    {'character': '真的', 'pinyin': 'zhēn  de', 'definition': 'really'},
    {'character': '正（副）', 'pinyin': 'zhèng', 'definition': 'just; exactly'},
    {'character': '正在', 'pinyin': 'zhèngzài  in process', 'definition': 'of'},
    {'character': '知道', 'pinyin': 'zhīdào', 'definition': 'know'},
    {'character': '知识', 'pinyin': 'zhīshi', 'definition': 'knowledge'},
    {'character': '中', 'pinyin': 'zhōng', 'definition': 'middle; in'},
    {'character': '中国', 'pinyin': 'zhōngguó', 'definition': 'China'},
    {'character': '中间', 'pinyin': 'zhōngjiān', 'definition': 'Middle'},
    {'character': '中文', 'pinyin': 'zhōngwén', 'definition': 'Chinese'},
    {'character': '中午', 'pinyin': 'zhōngwǔ', 'definition': 'Noon'},
    {'character': '中学', 'pinyin': 'zhōng  xué middle', 'definition': 'school'},
    {'character': '中学生', 'pinyin': 'zhōng', 'definition': 'xué'},
    {'character': '重', 'pinyin': 'zhòng', 'definition': 'heavy'},
    {'character': '重要', 'pinyin': 'zhòngyào', 'definition': 'important'},
    {'character': '住', 'pinyin': 'zhù', 'definition': 'live'},
    {'character': '准备', 'pinyin': 'zhǔnbèi  Get', 'definition': 'ready'},
    {'character': '桌子', 'pinyin': 'zhuōzi', 'definition': 'Table'},
    {'character': '字', 'pinyin': 'zì', 'definition': 'word, character'},
    {'character': '子（桌子）', 'pinyin': 'zi', 'definition': 'zhuō  zi'},
    {'character': '走', 'pinyin': 'zǒu', 'definition': 'go, walk'},
    {'character': '走路', 'pinyin': 'zǒu lù', 'definition': 'walk'},
    {'character': '最', 'pinyin': 'zuì', 'definition': 'most'},
    {'character': '最好', 'pinyin': 'zuìhǎo', 'definition': 'Best'},
    {'character': '最后', 'pinyin': 'zuìhòu', 'definition': 'Last'},
    {'character': '昨天', 'pinyin': 'zuótiān', 'definition': 'Yesterday'},
    {'character': '左', 'pinyin': 'zuǒ', 'definition': 'left'},
    {'character': '左边', 'pinyin': 'zuǒbian', 'definition': 'left'},
    {'character': '坐', 'pinyin': 'zuò', 'definition': 'sit'},
    {'character': '坐下', 'pinyin': 'zuò xià  sit', 'definition': 'down'},
    {'character': '做', 'pinyin': 'zuò', 'definition': 'do'},
]
